spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route for USER-SERVICE
        - id: user-service
          uri: lb://USER-SERVICE # Load-balances requests to USER-SERVICE
          predicates:
            - Path=/user/** # Routes matching /user/** are forwarded to USER-SERVICE
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL


server:
  port: 8765 # API Gateway port

jwt:
  secret: ${JWT_SECRET} # Replace with your actual JWT secret

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

