spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/product/**
            - Path=/category/**
            - Path=/inventory/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Path=/admin/**
      default-filters:
        - TokenRelay # Pass token to downstream services

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8765

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


