spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/product/**
            - Path=/category/**
            - Path=/inventory/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Path=/admin/**
      default-filters:
        - TokenRelay # Pass token to downstream services

server:
  port: 8765
