spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service-user
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/user/** 
          filters:
            - AuthenticationFilter
        - id: user-service-admin
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/admin/** 
          filters:
            - AuthenticationFilter

        - id: inventory-service-inventory
          uri: lb://INVENTORY-SERVICE 
          predicates:
            - Path=/inventory/** 
          filters:
            - AuthenticationFilter
        - id: inventory-service-product
          uri: lb://INVENTORY-SERVICE 
          predicates:
            - Path=/product/** 
          filters:
            - AuthenticationFilter
        - id: inventory-service-category
          uri: lb://INVENTORY-SERVICE 
          predicates:
            - Path=/category/** 
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL


server:
  port: 8765 #

jwt:
  secret: ${JWT_SECRET} # Replace with your actual JWT secret

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

