spring:
  application:
    name: security

  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security?useSSL=false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Podman56

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  logging:
#    level:
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

