spring:
  application:
    name: security

  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security?useSSL=false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Podman56

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

